#version: '3.8'
services:
  # Container internal address (hostname) : The address (service name) that containers look up for each other within a Docker network
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    #ports: 
    # - 3306:3306
    env_file: .env
    volumes:
    - mariadb_data:/var/lib/mysql
    networks:
    - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    restart: always
    expose:
      - "9000"
    #ports: 
    #  - 9000:9000
    env_file: .env
    depends_on:
    - mariadb
    volumes:
    - wordpress_data:/var/www/wordpress
    networks:
    - inception

  nginx:
    build: ./requirements/nginx #Dockerfile location
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: always
    depends_on:
    - wordpress
    ports:
      - "443:443" #host:container
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
    - inception # nginx <-> wordpress <-> mariadb connect

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jaoh/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jaoh/data/wordpress

networks:
  inception:
    driver: bridge
