[www]
user = www-data
group = www-data

; Listen on TCP port 9000 instead of unix socket
; This is how NGINX will reach php-fpm across containers
listen = 0.0.0.0:9000

listen.owner = www-data
listen.group = www-data

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Clear environment
clear_env = no
